spring.application.name=spring-jpa-usage-student
spring.datasource.url=jdbc:postgresql://localhost:5432/spring-jpa-student
spring.jpa.properties.hibernate.default_schema=student
spring.datasource.username=postgres
spring.datasource.password=111

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true